[package]
name = "vector_field_visualization"
version = "1.0.0"
authors = ["Zelda Hessler <zelda.hessler@pm.me>"]
edition = "2018"

[dependencies]
itertools = "0.10.0"
nannou = "0.16.0"
noise = "0.7.0"
rand = "0.8.3"
rayon = "1.5.0"
zelda_lib = { path = "../zelda_lib" }
