[package]
name = "vector_field_visualization"
version = "0.1.0"
authors = ["Zelda Hessler <zelda.hessler@pm.me>"]
edition = "2018"

[profile.release]
debug = true

[dependencies]
ggez = "^0.5"
rand = "^0.6"
noise = "^0.5"